# Generated by Django 3.1.7 on 2021-08-04 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0007_prosetting_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prophoto',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='tweet.prosetting'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prosetting',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
